GET http://localhost:3000/api/menu

###
POST http://localhost:3000/api/menu
Content-Type: application/json

  {
    "category": "Burger",
    "title": "New York Buffalo Burger",
    "description": "Southern Fried Chicken Thigh Fillets, Slaw, American Cheddar, Butteremilk Ranch, Burger sauce, Brioche Bun",
    "price": 999
  }

### 

GET http://localhost:3000/api/menu:id

###
PUT http://localhost:3000/api/menu/1c44beb1-f20a-484d-ad93-ad3aa4798651

  {
    "category": "Burger",
    "title": "New York Buffalo Burger",
    "description": "No ingredients",
    "price": 999,
  }

###
DELETE http://localhost:3000/api/menu/:id