GET http://localhost:3000/api/menu

###
POST http://localhost:3000/api/menu
Content-Type: application/json

  {
    "category": "Burger",
    "title": "New York Buffalo Burger",
    "description": "Southern Fried Chicken Thigh Fillets, Slaw, American Cheddar, Butteremilk Ranch, Burger sauce, Brioche Bun",
    "price": 999
  }

### 
PUT http://localhost:3000/api/menu/:id

###
DELETE http://localhost:3000/api/menu/:id