GET http://localhost:3000/api/menu

###
POST http://localhost:3000/api/menu
Content-Type: application/json

  {
    "category": "Burger",
    "title": "New York Buffalo Burger",
    "description": "Southern Fried Chicken Thigh Fillets, Slaw, American Cheddar, Butteremilk Ranch, Burger sauce, Brioche Bun",
    "price": 999
  }

### 

GET http://localhost:3000/api/menu/HBTQt
// the id above is the first item in data (cheeseburger)

###
PUT http://localhost:3000/api/menu
Content-Type: application/json

  {
    "category": "Burger",
    "title": "New York Buffalo Burger",
    "description": "No ingredients",
    "price": 799,
    "id": "_psaV"
  }
// id to be updated (if required)

###
DELETE http://localhost:3000/api/menu/ne6OD
// id should be updated in the link before sending a request