GET http://localhost:8080/api/menu

###
POST http://localhost:8080/api/menu
Content-Type: application/json

  {
    "category": "Burgers",
    "title": "New York Buffalo Burger",
    "description": "Southern Fried Chicken Thigh Fillets, Slaw, American Cheddar, Butteremilk Ranch, Burger sauce, Brioche Bun",
    "price": 999
  }

### 

GET http://localhost:8080/api/menu/HBTQt
// the above id is for the first item (cheeseburger) in data
// update if it doesn't exist

###
PUT http://localhost:8080/api/menu
Content-Type: application/json

  {
    "category": "Burgers",
    "title": "New York Buffalo Burger",
    "description": "No ingredients",
    "price": 799,
    "id": "en_Ab"
  }
// id to be updated in the object (if needed)

###
DELETE http://localhost:8080/api/menu/en_Ab
 // id to be updated in the url