GET http://localhost:8080/api/menu

###
POST http://localhost:8080/api/menu
Content-Type: application/json

  {
    "category": "Burger",
    "title": "New York Buffalo Burger",
    "description": "Southern Fried Chicken Thigh Fillets, Slaw, American Cheddar, Butteremilk Ranch, Burger sauce, Brioche Bun",
    "price": 999
  }

### 

GET http://localhost:8080/api/menu/ZurG9
// id should be updated

###
PUT http://localhost:8080/api/menu
Content-Type: application/json

  {
    "category": "Burger",
    "title": "New York Buffalo Burger",
    "description": "No ingredients",
    "price": 799,
    "id": "ZurG9"
  }
// id to be updated (if required)

###
DELETE http://localhost:8080/api/menu/ZurG9
// id should be updated in the link before sending a request